db.url=jdbc:mariadb://127.0.0.1:3307/carely
db.username=root
db.password=
db.runMigrations=false
db.pool.name=CarelyPool
db.pool.maximumPoolSize=10
db.pool.minimumIdle=2
db.pool.connectionTimeoutMs=30000
db.pool.idleTimeoutMs=600000
db.pool.maxLifetimeMs=1800000
